# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cac1b851272bd53b02b76fcca2c343bfd1b038b5be88da471426a6b8770457b7a85df6f6296c9e1ab40eba7ac2ac352b467f4e218fbb56308fa2ad291574083

test:
  secret_key_base: 0c3139a528e87e77567ca469b58312cb8cbf860375e53d00efeb352ac96b721a04327c6ceea9396d1a226e2645bda503e68bbd84e017cbbd191d360688637402

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
